title: "CSS485 - Artificial Neural Networks"
description: "Course Materials for Neural Networks"
baseurl: "/css485-ann-uwb-sp2025"
url: "https://mrrahman1517.github.io"
theme: minima
exclude: ["README.md"]
nav_links:
  - title: "Home"
    url: "/"
  - title: "ANN Winter 2025"
    url: "/winter2025/"
  - title: "ANN Winter 2026"
    url: "/winter2026/"
